description:
  DisplayName: Magic Cape
  Category: Gear
  Description: This cape allows you to magically fly while standing upright.
  Usage: Hit JUMP in midair to start flying. Land on solid ground or hit JUMP twice to disengage.